---
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.261"
    hooks:
      - id: ruff
        args:
          - "--fix"
          - "--exit-non-zero-on-fix"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-toml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.31.0
    hooks:
      - id: cspell
        name: Spell check with cspell

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
        args:
          - --strict
        types: [file, yaml]

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint

  - repo: https://github.com/pycqa/pylint
    rev: v2.17.1
    hooks:
      - id: pylint
        additional_dependencies:
          - ansible-core
          - antsibull-docs-parser
          - pyyaml
          - redbaron
          - ruamel.yaml
