---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  # All dot files in the root
  - \.*
  # This file
  - cspell.config.yaml
  # Ignore licenses
  - licenses/*
  # The shared file for tool configuration
  - pyproject.toml
  # The setup file
  - setup.cfg
  # requirements.txt is generated
  - requirements.txt
